service: aws-localstack
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  
plugins:
  - serverless-offline

functions:
  api:
    handler: ./src/index.handler
    events:
      - httpApi:
          path: /
          method: get
